import { StyleSheet } from 'react-native';
import Layout from '../../constants/Layout';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  adModalWrap: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: 99,
    elevation: 99,
  },
  adModalBg: {
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  adModalBox: {
    position: 'absolute',
    top: '26%',
    left: 0,
    width: '100%',
    paddingLeft: 65,
    paddingRight: 65,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  adModalImgWrap: {
    width: '100%',
    height: 260,
    backgroundColor: '#f60',
    borderRadius: 20,
    overflow: 'hidden',
  },
  adModalImg: {
    width: '100%',
    height: '100%',
  },
  adModalCloseBox: {
    width: 39,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  adModalCloseLine: {
    height: 48,
    width: 2,
    backgroundColor: '#fff',
    marginLeft: 10,
    marginRight: 10,
  },
  adModalCloseBtn: {
    marginTop: -5,
  },
  refreshingTextWrap: {
    position: 'absolute',
    top: 70,
    left: 0,
    zIndex: 3,
    width: Layout.window.width,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  refreshingText: {
    fontSize: 14,
    color: '#fff',
    fontFamily: 'PingFangSC-Regular',
  },
  loadingTextWrap: {
    width: Layout.window.width,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  loadingTextEmpty: {
    marginTop: 200,
  },
  loadingText: {
    fontSize: 14,
    color: '#999',
    fontFamily: 'PingFangSC-Regular',
  },
  recommend: {
    width: Layout.window.width,
    overflow: 'hidden',
  },
  linearGradient: {
    position: 'absolute',
    width: '100%',
    height: 217,
  },
  searchBox: {
    marginTop: 50,
    marginRight: 12,
    marginLeft: 12,
    borderRadius: 16,
  },
  shopName: {
    fontSize: 20,
    color: '#fff',
    fontFamily: 'PingFangSC-Semibold',
    flex: 1,
    marginLeft: 6,
    marginRight: 6,
    textAlign: 'center',
  },
  headBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 32,
  },
  searchIcon: {
    width: 18,
    height: 18,
    marginRight: 8,
  },
  searchInput: {
    width: '100%',
    height: 32,
    marginTop: 12,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  searchText: {
    fontFamily: 'PingFangSC-Regular',
    fontSize: 14,
    lineHeight: 22,
    color: '#999',
    textAlign: 'left',
  },
  topTabtextStyle: {
    color: '#fff',
    fontFamily: 'PingFangSC-Medium',
  },
  topTabLineStyle: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
  },
  tabs: {
    fontSize: 14,
    color: '#fff',
    marginRight: 24,
    fontFamily: 'PingFangSC-Medium',
  },
  tabOnly: {
    fontSize: 18,
    color: '#fff',
    fontWeight: 'bold',
    marginLeft: 20,
    marginTop: 6,
  },
  wrapper: {
    width: Layout.window.width,
  },
  text: {
    color: '#fff',
    fontSize: 30,
    fontWeight: 'bold',
  },
  bannerWrap: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    height: 142,
  },
  category: {
    paddingTop: 15,
    paddingLeft: 6,
    paddingRight: 6,
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    flexDirection: 'row',
    backgroundColor: '#fff',
  },
  categoryFour: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  categoryItem: {
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  activityItem: {
    width: 60,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  categoryImg: {
    width: 60,
    height: 60,
    resizeMode: 'cover',
    marginBottom: 5,
  },
  activityImg: {
    width: 48,
    height: 48,
    resizeMode: 'cover',
    marginBottom: 5,
  },
  categoryImgText: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginBottom: 5,
    backgroundColor: 'transparent',
  },
  categoryText: {
    fontFamily: 'PingFangSC-Regular',
    fontSize: 12,
    color: '#666',
    textAlign: 'center',
  },
  activityText: {
    fontFamily: 'PingFangSC-Regular',
    fontSize: 12,
    color: '#666',
    textAlign: 'center',
  },
  productsWrap: {
    backgroundColor: '#f4f4f4',
  },
  parentCategoryWrap: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 18,
    paddingRight: 18,
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: '#fff',
    width: '100%',
  },
  parentCategoryContent: {
    width: '100%',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
  },
  sortTabsWrap: {
    borderTopWidth: 10,
    borderBottomWidth: 10,
    borderTopColor: '#f4f4f4',
    borderBottomColor: '#f4f4f4',
    backgroundColor: '#fff',
  },
  categoryPrdWrap: {
    backgroundColor: '#f4f4f4',
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 8,
  },
  adJump: {
    width: '100%',
    alignItems: 'center',
    paddingBottom: 16,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: '#fff',
  },
  adImg: {
    width: '100%',
    height: 60,
    backgroundColor: '#f4f4f4',
    borderRadius: 8,
  },
  mlshNoticeWrap: {
    position: 'relative',
    width: '100%',
    justifyContent: 'center',
    backgroundColor: '#fff',
    height: 52,
  },
  noticeWrap: {
    position: 'absolute',
    top: '50%',
    left: '32%',
    marginTop: -22,
    width: '62%',
    height: 34,
    justifyContent: 'center',
  },
  mlshNotice: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
  },
  mlshNoticeText: {
    fontFamily: 'PingFangSC-Regular',
    fontSize: 12,
    color: '#333',
  },
  mlshNoticeImg: {
    width: '100%',
    height: '100%',
    marginBottom: 10,
  },
  prefectureWrap: {
    width: '100%',
    backgroundColor: '#fff',
  },
  prefectureContent: {
    width: '100%',
    marginHorizontal: '3%',
    flexWrap: 'wrap',
    flexDirection: 'row',
    marginBottom: 17,
  },
  prefectureItem: {
    width: '47%',
  },
  prefectureImg: {
    width: '100%',
    height: 140,
  },
  shoppingCart: {
    width: 26,
    height: 21,
  },
  scanIcon: {
    width: 26,
    height: 21,
  },
  footer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
});
